# Generated by Django 5.0.6 on 2026-02-23 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(max_length=255, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('result_code', models.CharField(blank=True, max_length=20)),
                ('result_desc', models.TextField(blank=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['checkout_request_id'], name='payments_pa_checkou_cc4d34_idx'), models.Index(fields=['status'], name='payments_pa_status_b6726a_idx'), models.Index(fields=['created_at'], name='payments_pa_created_a246c6_idx')],
            },
        ),
    ]
