# Generated by Django 5.0.6 on 2026-02-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'), models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx'), models.Index(fields=['brand'], name='products_pr_brand_4bfaa4_idx'), models.Index(fields=['is_featured'], name='products_pr_is_feat_a5d7cd_idx'), models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx')],
            },
        ),
    ]
